name: CI
on: [push]
jobs:
  lhci:
    name: Run Lighthouse CI on Shopify theme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run Lighthouse CI on Shopify theme
        uses: Shopify/lighthouse-ci-action@v1.2.2
        with:
          store: ${{ secrets.SHOP_STORE_OS2 }}
          password: ${{ secrets.SHOP_PASSWORD_OS2 }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          collection_handle: all
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}
          pull_theme: ${{ secrets.SHOP_PULL_THEME }}
  theme-check:
    name: Run Theme Check on Shopify theme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run Theme Check on Shopify theme
        uses: Shopify/theme-check-action@v2.2.0
        with:
          token: ${{ github.token }}
